from roots import Root, sum_root, mult_root
from scalar_products import scalarp_roots

def weyl(roota: Root,rootb: Root):
    '''
    Weyl reflection of root b generated by root a
    '''
    if roota.vect_array==rootb.vect_array:
        if roota.coeffs==rootb.coeffs:
            return mult_root(roota,-1)
        elif roota.length!=0:
            proj=mult_root(roota,-2*scalarp_roots(roota,rootb)/roota.length)
            return sum_root(rootb,proj)
        elif roota.length==0:
            if scalarp_roots(roota,rootb)==0:
                return rootb
            else:
                return sum_root(roota,rootb)
    else:
        raise ValueError