from roots import *

def weyl(roota: Root,rootb: Root):
    '''
    Weyl reflection of root b generated by root a
    '''
    if roota.vect_array==rootb.vect_array:
        return mult_root(root,-1)
    elif 
